name: ci

on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  test:
    defaults:
      run:
        working-directory: go/src/github.com/TUB-CNPE-TB/payment
    runs-on: ubuntu-latest
    env:
      GROUP: europe-west3-docker.pkg.dev/cnpe-blue/sockshop
      COMMIT: ${{ github.sha }}
      REPO: payment
      GO_VERSION: 1.7.5
      GOPATH: /home/runner/work/payment/payment/go

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/TUB-CNPE-TB/payment

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup PATH
        run: echo "${GOPATH}/bin" >> $GITHUB_PATH

      - name: Build payment image
        uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
        with:
          push: false
          dockerfile: go/src/github.com/TUB-CNPE-TB/docker/payment/Dockerfile
          tags: payment:latest
          path: go/src/github.com/TUB-CNPE-TB/payment
          repository: ${{ env.GROUP }}/${{ env.REPO }}
          tag_with_ref: true
          tag_with_sha: true
          
      # Push to GAR 
      - name: Login to GAR
        uses: docker/login-action@v1
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
        with:
          registry: europe-west3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Push to GAR
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
        run: docker push ${{ env.GROUP }}/${{ env.REPO }} --all-tags  
